pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: deluge-dev

  test:
    image: spritsail/docker-test
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: deluge-dev
    delay: 3
    verbose: true
    curl_opts: -o/dev/null -sS
    # Test deluge-web is running and responding
    curl: ':8112'
    # Add a user and attempt connecting to the daemon
    exec_post: |
      echo "username:password:10" >> /config/auth;
      deluge-console -l /dev/stdout -L info "connect localhost username password; quit"
          | tee /dev/stderr
          | grep -qF "Connection was closed cleanly"

  publish:
    image: spritsail/docker-publish
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    when: { branch: [ master], event: [ push, tag, deployment ] }
    from: deluge-dev
    repo: spritsail/deluge
    tags:
      - 'latest'
      - '%label io.spritsail.version.deluge | %auto'

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
