---
kind: pipeline
name: deluge

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build
  settings:
    repo: deluge-dev

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    repo: deluge-dev
    delay: 3
    verbose: true
    curl_opts: -o/dev/null -sS
    curl: ':8112'
    # Add a user and attempt connecting to the daemon
    exec_post: |
      echo "username:password:10" >> /config/auth;
      sleep 2; # wait for deluged to detect auth change
      deluge-console -l /dev/stdout -L deluge "connect localhost username password; quit"
          | tee /dev/stderr
          | grep -qF "Connection was closed cleanly"

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    from: deluge-dev
    repo: spritsail/deluge
    tags:
    - latest
    - "%label io.spritsail.version.deluge | %auto"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: b2b81d19f8fe1c3198771372bc2d77a0359eced91bb069ed830e791473b1d930

...
